language: python
python:
  - 2.7
env:
  - PLONE_VERSION=4.3
install:
  - sed -ie "s#travis-4.x.cfg#travis-$PLONE_VERSION.x.cfg#" travis.cfg
  - mkdir -p buildout-cache/downloads
  - python bootstrap.py -c travis.cfg
  - bin/buildout -c travis.cfg -N -q -t 3
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
script: 
  - bin/test
  - if [ "$BROWSER" == "code-analysis" ]; then bin/flake8 setup.py; fi
  - if [ "$BROWSER" == "code-analysis" ]; then bin/flake8 plonetesting; fi
  - if [ "$BROWSER" == "code-analysis" ]; then bin/coverage run --source=plonetesting.content --omit=plonetesting/content/test\* bin/test; fi
after_success:
  - bin/coveralls
